services:
  postgres:
    image: postgres:15-alpine
    container_name: vk_db_container
    environment:
      POSTGRES_USER: srie
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: vk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: